db.foods.insert({"foodname" : "Potato" });
db.foods.insert({"foodname" : "Chocolate" });
db.foods.insert({"foodname" : "Black Pepper" });
db.foods.insert({"foodname" : "Strawberries" });
db.foods.insert({"foodname" : "Fish" });
db.foods.insert({"foodname" : "Milk (Goat)" });
db.foods.insert({"foodname" : "Milk (Cow)" });
db.foods.insert({"foodname" : "Wheat" });
db.foods.insert({"foodname" : "Shellfish" });
db.foods.insert({"foodname" : "Egg" });
db.foods.insert({"foodname" : "Peas" });
db.foods.insert({"foodname" : "Sweet Potato" });
db.foods.insert({"foodname" : "Peanut" });
db.foods.insert({"foodname" : "Tree Nuts" });
db.foods.insert({"foodname" : "Mango" });
db.foods.insert({"foodname" : "Corn" });
db.foods.insert({"foodname" : "Oat" });
db.foods.insert({"foodname" : "Rice" });
db.foods.insert({"foodname" : "Soybean" });
db.foods.insert({"foodname" : "Yeast-Brewers" });
db.foods.insert({"foodname" : "Casein" });
db.foods.insert({"foodname" : "Egg White" });
db.foods.insert({"foodname" : "Egg Yolk" });
db.foods.insert({"foodname" : "Beef" });
db.foods.insert({"foodname" : "Chicken" });
db.foods.insert({"foodname" : "Turkey" });
db.foods.insert({"foodname" : "Clam" });
db.foods.insert({"foodname" : "Cod Mix" });
db.foods.insert({"foodname" : "Crab" });
db.foods.insert({"foodname" : "Flounder" });
db.foods.insert({"foodname" : "Salmon" });
db.foods.insert({"foodname" : "Shrimp" });
db.foods.insert({"foodname" : "Tuna" });
db.foods.insert({"foodname" : "Apple" });
db.foods.insert({"foodname" : "Banana" });
db.foods.insert({"foodname" : "Grape" });
db.foods.insert({"foodname" : "Orange" });
db.foods.insert({"foodname" : "Peach" });
db.foods.insert({"foodname" : "Pear" });
db.foods.insert({"foodname" : "Pineapple" });
db.foods.insert({"foodname" : "Almond" });
db.foods.insert({"foodname" : "Cashew" });
db.foods.insert({"foodname" : "Hazlenut" });
db.foods.insert({"foodname" : "Pecan" });
db.foods.insert({"foodname" : "Walnut" });
db.foods.insert({"foodname" : "Sunflower Seed" });
db.foods.insert({"foodname" : "Pistachio" });
db.foods.insert({"foodname" : "Basil" });
db.foods.insert({"foodname" : "Cinnamon" });
db.foods.insert({"foodname" : "Cottonseed" });
db.foods.insert({"foodname" : "Coffee" });
db.foods.insert({"foodname" : "Garlic" });
db.foods.insert({"foodname" : "Oregano" });
db.foods.insert({"foodname" : "Tea" });
db.foods.insert({"foodname" : "Dill" });
db.foods.insert({"foodname" : "Ginger" });
db.foods.insert({"foodname" : "Nutmeg" });
db.foods.insert({"foodname" : "Mustard" });
db.foods.insert({"foodname" : "Parsley" });
db.foods.insert({"foodname" : "Sesame" });
db.foods.insert({"foodname" : "Vanilla" });
db.foods.insert({"foodname" : "String Beans" });
db.foods.insert({"foodname" : "Gum - Karaya" });
db.foods.insert({"foodname" : "Gum - Tragacanth" });
db.foods.insert({"foodname" : "Broccoli" });
db.foods.insert({"foodname" : "Carrot" });
db.foods.insert({"foodname" : "Mushroom" });
db.foods.insert({"foodname" : "Olive" });
db.foods.insert({"foodname" : "Onion" });
db.foods.insert({"foodname" : "Green Pepper" });
db.foods.insert({"foodname" : "Tomato" });
db.foods.insert({"foodname" : "Honeydew" });
db.foods.insert({"foodname" : "Blueberry" });
db.foods.insert({"foodname" : "Canatloupe" });
db.foods.insert({"foodname" : "Cherry" });
db.foods.insert({"foodname" : "Cranberry" });
db.foods.insert({"foodname" : "Plum" });
db.foods.insert({"foodname" : "Raspberry" });
db.foods.insert({"foodname" : "Barley" });
db.foods.insert({"foodname" : "Malt" });
db.foods.insert({"foodname" : "Lemon" });
db.foods.insert({"foodname" : "Gum - Arabic" });
db.foods.insert({"foodname" : "Coconut" });
db.foods.insert({"foodname" : "Celery" });
db.foods.insert({"foodname" : "Sage" });
db.foods.insert({"foodname" : "Thyme" });
db.foods.insert({"foodname" : "Cauliflower" });
db.foods.insert({"foodname" : "Cucumber" });
db.foods.insert({"foodname" : "Lettuce" });
db.foods.insert({"foodname" : "Spinach" });
db.foods.insert({"foodname" : "Asparagus" });
db.foods.insert({"foodname" : "Buckwheat" });
db.foods.insert({"foodname" : "Hops" });
db.foods.insert({"foodname" : "Rye" });
db.foods.insert({"foodname" : "Halibut" });
db.foods.insert({"foodname" : "Lobster" });
db.foods.insert({"foodname" : "Oyster Mix" });
db.foods.insert({"foodname" : "Trout" });
db.foods.insert({"foodname" : "Apricot" });
db.foods.insert({"foodname" : "Grapefruit" });
db.foods.insert({"foodname" : "Lime" });
db.foods.insert({"foodname" : "Mint" });
db.foods.insert({"foodname" : "Lamb" });
db.foods.insert({"foodname" : "Pork" });
db.foods.insert({"foodname" : "Flaxseed" });
db.foods.insert({"foodname" : "Paprika" });
db.foods.insert({"foodname" : "Cumin" });
db.foods.insert({"foodname" : "Squash - Italian" });
db.foods.insert({"foodname" : "Squash - Summer" });
db.foods.insert({"foodname" : "Eggplant" });
db.foods.insert({"foodname" : "Lentil" });
db.foods.insert({"foodname" : "Bot. Cinerea" });
db.foods.insert({"foodname" : "Bean - Kidney" });
db.foods.insert({"foodname" : "Bean - Lima" });
db.foods.insert({"foodname" : "Bean - Pinto" });
db.foods.insert({"foodname" : "Blood Orange" });
db.foods.insert({"foodname" : "Bean - Navy" });
db.foods.insert({"foodname" : "Watermelon" });
db.foods.insert({"foodname" : "Gum - Guar" });
db.foods.insert({"foodname" : "Egg (Quail)" });